CREATE DATABASE RESTO_DB
GO
USE RESTO_DB
GO

SET LANGUAGE Spanish;
GO

/*	ROLES USUARIO	*/
CREATE TABLE Roles(
	IDROL INT IDENTITY(1,1),
	NOMBRE VARCHAR(50) NOT NULL,

	PRIMARY KEY(IDROL)
)
GO

/*	TABLA USUARIOS	*/
CREATE TABLE Usuarios(
	IDUSUARIO BIGINT IDENTITY(1,1),
	NOMBRE VARCHAR(50) NOT NULL,
	CONTRASENIA VARCHAR(50) NOT NULL,
	ESTADO BIT DEFAULT 1,
	IDROL INT,

	PRIMARY KEY(IDUSUARIO),
	FOREIGN KEY(IDROL) REFERENCES Roles(IDROL)
)
GO

/*	TABLA DIRECCIONES	*/
CREATE TABLE Direcciones(
	IDDIRECCION BIGINT IDENTITY(1,1),
	CALLE VARCHAR(50) NOT NULL,
	NUM_DIRECCION VARCHAR(4) NOT NULL,
	LOCALIDAD VARCHAR(100) NOT NULL,
	COD_POSTAL VARCHAR(5) NOT NULL,

	PRIMARY KEY(IDDIRECCION),
)
GO

CREATE TABLE Empleados(
	IDEMPLEADO BIGINT IDENTITY(1,1),
	IDUSUARIO BIGINT,
	IDDIRECCION BIGINT,
	NOMBRE VARCHAR(100) NOT NULL,
	APELLIDO VARCHAR(100) NOT NULL,
	DOCUMENTO VARCHAR(10) NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	FECHA_INGRESO DATE DEFAULT GETDATE(),
	EMAIL VARCHAR(100),
	TELEFONO VARCHAR(15),

	PRIMARY KEY(IDEMPLEADO),
	FOREIGN KEY(IDUSUARIO) REFERENCES Usuarios(IDUSUARIO),
	FOREIGN KEY(IDDIRECCION) REFERENCES Direcciones(IDDIRECCION)
)

/*	TABLA MESAS	*/
CREATE TABLE Mesas(
	IDMESA BIGINT IDENTITY(1,1),
	NUMERO INT NOT NULL,
	ESTADO VARCHAR(100) NOT NULL,
	IDUSUARIO BIGINT,

	PRIMARY KEY(IDMESA),
	FOREIGN KEY(IDUSUARIO) REFERENCES Usuarios(IDUSUARIO),
	CONSTRAINT CHK_ESTADO CHECK(ESTADO IN ('DISPONIBLE','OCUPADA','CERRADA'))
)
GO

CREATE TABLE Categorias(
	IDCATEGORIA BIGINT IDENTITY(1,1),
	NOMBRE VARCHAR(50) NOT NULL,

	PRIMARY KEY(IDCATEGORIA)
)
GO

/*	TABLA PRODUCTOS	*/
CREATE TABLE Productos(
	IDPRODUCTO BIGINT IDENTITY(1,1),
	IDCATEGORIA BIGINT,
	NOMBRE VARCHAR(100) NOT NULL,
	PRECIO MONEY NOT NULL,
	STOCK INT NOT NULL,
	DESCRIPCION TEXT NOT NULL,
	ESTADO BIT DEFAULT 1,
	
	PRIMARY KEY(IDPRODUCTO),
)
GO


CREATE TABLE Entradas(
	IDPRODUCTO BIGINT,
	INDIVIDUAL BIT NOT NULL DEFAULT 0
)
GO


CREATE TABLE Postres(
	IDPRODUCTO BIGINT,
	GLUTEN BIT DEFAULT 0,
	AZUCAR BIT DEFAULT 0
)
GO

CREATE TABLE Bebidas(
	IDPRODUCTO BIGINT,
	ALCOHOL BIT DEFAULT 0,
	VOLUMEN INT NOT NULL,
)
GO

/*	TABLA PEDIDOS	*/
CREATE TABLE Pedidos(
	IDPEDIDO BIGINT IDENTITY(1,1),
	IDMESA BIGINT,
	IDUSUARIO BIGINT,
	ESTADO VARCHAR(100)
	
	PRIMARY KEY(IDPEDIDO),
	FOREIGN KEY(IDMESA) REFERENCES Mesas(IDMESA),
	FOREIGN KEY(IDUSUARIO) REFERENCES Usuarios(IDUSUARIO)
)
GO

/*	TABLE DETALLES PEDIDO	*/
CREATE TABLE DetallesPedido(
	IDDETALLE BIGINT IDENTITY(1,1),
	IDPEDIDO BIGINT,
	IDPRODUCTO BIGINT,
	CANTIDAD INT NOT NULL,
	SUBTOTAL MONEY NOT NULL,

	PRIMARY KEY(IDDETALLE),
	FOREIGN KEY(IDPEDIDO) REFERENCES Pedidos(IDPEDIDO),
	FOREIGN KEY(IDPRODUCTO) REFERENCES Productos(IDPRODUCTO)
)
GO

/*	TABLA VENTAS	*/
CREATE TABLE Ventas(
	IDVENTA BIGINT IDENTITY(1,1),
	IDPEDIDO BIGINT,
	IDUSUARIO BIGINT,
	FECHA_HORA DATETIME NOT NULL DEFAULT GETDATE(),
	TOTAL MONEY NOT NULL,

	PRIMARY KEY(IDVENTA),
	FOREIGN KEY(IDPEDIDO) REFERENCES Pedidos(IDPEDIDO),
	FOREIGN KEY(IDUSUARIO) REFERENCES Usuarios(IDUSUARIO)
)
GO



/******* Inputs *******/

/*	Roles de usuario --> ampliable	*/
INSERT INTO Roles(NOMBRE)
VALUES ('GERENTE'),('MOZO')

/*	Usuarios	*/
INSERT INTO Usuarios(NOMBRE,CONTRASENIA,IDROL)
VALUES ('Master','Master',1)
INSERT INTO Usuarios(NOMBRE,CONTRASENIA,IDROL)
VALUES ('Test','Test',2)

INSERT INTO Direcciones(CALLE,NUM_DIRECCION,LOCALIDAD,COD_POSTAL)
VALUES 
('Martin Rodriguez','2061','Villa Adelina','1607'),
('Entre Rios','4089','Munro','1605')

INSERT INTO Empleados(IDUSUARIO,IDDIRECCION,NOMBRE,APELLIDO,DOCUMENTO,FECHA_NACIMIENTO,EMAIL,TELEFONO)
VALUES
(1,1,'Brian','Barrera','42832435','2000/08/02','Master@gmail.com','1167624662'),
(2,2,'Doris','Gomez','94256338','1969/04/24','Test@gmial.com','1138833931')

/******* Productos *******/

INSERT INTO Categorias(NOMBRE)
VALUES ('CAFETERIA'),('ENTRADAS'),('COMIDAS'),('POSTRES'),('BEBIDAS')




