USE RESTO_DB
GO

/*		Usuarios		*/

CREATE VIEW vw_ListaEmpleados
AS
SELECT E.IDEMPLEADO,E.IDUSUARIO,E.NOMBRE,E.APELLIDO,E.DOCUMENTO,E.FECHA_NACIMIENTO,
	   E.FECHA_INGRESO,D.IDDIRECCION,D.CALLE,D.NUM_DIRECCION,D.LOCALIDAD,D.COD_POSTAL,
	   E.EMAIL,E.TELEFONO,U.IDROL,U.ESTADO 
FROM EMPLEADOS E
INNER JOIN Usuarios U ON E.IDUSUARIO = U.IDUSUARIO
INNER JOIN Direcciones D ON E.IDDIRECCION = D.IDDIRECCION
GO

SELECT IDEMPLEADO,IDUSUARIO,NOMBRE,APELLIDO,DOCUMENTO,FECHA_NACIMIENTO,FECHA_INGRESO,IDDIRECCION,CALLE,NUM_DIRECCION,LOCALIDAD,COD_POSTAL,EMAIL,TELEFONO,IDROL,ESTADO FROM vw_ListaEmpleados


