CREATE DATABASE RESTO_DB
GO
USE RESTO_DB
GO

/*	ROLES USUARIO	*/
CREATE TABLE Roles(
	IDROL INT IDENTITY(1,1),
	NOMBRE VARCHAR(50) NOT NULL,

	PRIMARY KEY(IDROL)
)
GO

/*	TABLA USUARIOS	*/
CREATE TABLE Usuarios(
	IDUSUARIO BIGINT IDENTITY(1,1),
	NOMBRE VARCHAR(50) NOT NULL,
	CONTRASENIA VARCHAR(50) NOT NULL,
	ESTADO BIT DEFAULT 1,
	IDROL INT,

	PRIMARY KEY(IDUSUARIO),
	FOREIGN KEY(IDROL) REFERENCES Roles(IDROL)
)
GO

/*	TABLA MOZOS*/
CREATE TABLE Mozos(
	IDMOZO BIGINT IDENTITY(1,1),
	NOMBRE VARCHAR(100) NOT NULL,
	APELLIDO VARCHAR(100) NOT NULL,
	IDUSUARIO BIGINT,

	PRIMARY KEY(IDMOZO),
	FOREIGN KEY(IDUSUARIO) REFERENCES Usuarios(IDUSUARIO)
)
GO

/*	TABLA GERENTES*/
CREATE TABLE Gerentes(
	IDGERENTE BIGINT IDENTITY(1,1),
	NOMBRE VARCHAR(100) NOT NULL,
	APELLIDO VARCHAR(100) NOT NULL,
	IDUSUARIO BIGINT,

	PRIMARY KEY(IDGERENTE),
	FOREIGN KEY(IDUSUARIO) REFERENCES Usuarios(IDUSUARIO)
)
GO

/*	TABLA MESAS	*/
CREATE TABLE Mesas(
	IDMESA BIGINT IDENTITY(1,1),
	NUMERO INT NOT NULL,
	ESTADO VARCHAR(100) NOT NULL,
	IDUSUARIO BIGINT,

	PRIMARY KEY(IDMESA),
	FOREIGN KEY(IDUSUARIO) REFERENCES Usuarios(IDUSUARIO),
	CONSTRAINT CHK_ESTADO CHECK(ESTADO IN ('DISPONIBLE','OCUPADA','CERRADA'))
)
GO

/*	TABLA PRODUCTOS	*/
CREATE TABLE Productos(
	IDPRODUCTO BIGINT IDENTITY(1,1),
	NOMBRE VARCHAR(100) NOT NULL,
	PRECIO MONEY NOT NULL,
	STOCK INT NOT NULL,
	
	PRIMARY KEY(IDPRODUCTO)
)
GO

/*	TABLA PEDIDOS	*/
CREATE TABLE Pedidos(
	IDPEDIDO BIGINT IDENTITY(1,1),
	IDMESA BIGINT,
	IDUSUARIO BIGINT,
	--ESTADO VARCHAR(100)
	
	PRIMARY KEY(IDPEDIDO),
	FOREIGN KEY(IDMESA) REFERENCES Mesas(IDMESA),
	FOREIGN KEY(IDUSUARIO) REFERENCES Usuarios(IDUSUARIO)
)
GO

/*	TABLE DETALLES PEDIDO	*/
CREATE TABLE DetallesPedido(
	IDDETALLE BIGINT IDENTITY(1,1),
	IDPEDIDO BIGINT,
	IDPRODUCTO BIGINT,
	CANTIDAD INT NOT NULL,
	SUBTOTAL MONEY NOT NULL,

	PRIMARY KEY(IDDETALLE),
	FOREIGN KEY(IDPEDIDO) REFERENCES Pedidos(IDPEDIDO),
	FOREIGN KEY(IDPRODUCTO) REFERENCES Productos(IDPRODUCTO)
)
GO

/*	TABLA VENTAS	*/
CREATE TABLE Ventas(
	IDVENTA BIGINT IDENTITY(1,1),
	IDPEDIDO BIGINT,
	IDUSUARIO BIGINT,
	FECHA_HORA DATETIME NOT NULL DEFAULT GETDATE(),
	TOTAL MONEY NOT NULL,

	PRIMARY KEY(IDVENTA),
	FOREIGN KEY(IDPEDIDO) REFERENCES Pedidos(IDPEDIDO),
	FOREIGN KEY(IDUSUARIO) REFERENCES Usuarios(IDUSUARIO)
)
GO