CREATE DATABASE RESTO_DB
GO
USE RESTO_DB
GO

SET LANGUAGE Spanish;
GO

/*	ROLES USUARIO	*/
CREATE TABLE Roles(
	IDROL INT IDENTITY(1,1),
	NOMBRE VARCHAR(50) NOT NULL,

	PRIMARY KEY(IDROL)
)
GO

/*	TABLA USUARIOS	*/
CREATE TABLE Usuarios(
	IDUSUARIO BIGINT IDENTITY(1,1),
	NOMBRE VARCHAR(50) NOT NULL,
	CONTRASENIA VARCHAR(50) NOT NULL,
	ESTADO BIT DEFAULT 1,
	IDROL INT,

	PRIMARY KEY(IDUSUARIO),
	FOREIGN KEY(IDROL) REFERENCES Roles(IDROL)
)
GO

/*	TABLA DIRECCIONES	*/
CREATE TABLE Direcciones(
	IDDIRECCION BIGINT IDENTITY(1,1),
	CALLE VARCHAR(50) NOT NULL,
	NUM_DIRECCION VARCHAR(4) NOT NULL,
	LOCALIDAD VARCHAR(100) NOT NULL,
	COD_POSTAL VARCHAR(5),

	PRIMARY KEY(IDDIRECCION),
)
GO

CREATE TABLE Personas(
	IDPERSONA BIGINT IDENTITY(1,1),
	IDUSUARIO BIGINT,
	IDDIRECCION BIGINT,
	NOMBRE VARCHAR(100) NOT NULL,
	APELLIDO VARCHAR(100) NOT NULL,
	DOCUMENTO VARCHAR(10) NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	FECHA_INGRESO DATE DEFAULT GETDATE(),
	EMAIL VARCHAR(100),
	TELEFONO VARCHAR(15),
	ESTADO BIT DEFAULT 1,

	PRIMARY KEY(IDPERSONA),
	FOREIGN KEY(IDUSUARIO) REFERENCES Usuarios(IDUSUARIO),
	FOREIGN KEY(IDDIRECCION) REFERENCES Direcciones(IDDIRECCION)
)


/*	TABLA MOZOS*/
CREATE TABLE Mozos(
	IDMOZO BIGINT IDENTITY(1,1),
	IDPERSONA BIGINT,

	PRIMARY KEY(IDMOZO),
	FOREIGN KEY(IDPERSONA) REFERENCES Personas(IDPERSONA),
)
GO

/*	TABLA GERENTES*/
CREATE TABLE Gerentes(
	IDGERENTE BIGINT IDENTITY(1,1),
	IDPERSONA BIGINT,

	PRIMARY KEY(IDGERENTE),
	FOREIGN KEY(IDPERSONA) REFERENCES Personas(IDPERSONA),
)
GO

/*	TABLA MESAS	*/
CREATE TABLE Mesas(
	IDMESA BIGINT IDENTITY(1,1),
	NUMERO INT NOT NULL,
	ESTADO VARCHAR(100) NOT NULL,
	IDUSUARIO BIGINT,

	PRIMARY KEY(IDMESA),
	FOREIGN KEY(IDUSUARIO) REFERENCES Usuarios(IDUSUARIO),
	CONSTRAINT CHK_ESTADO CHECK(ESTADO IN ('DISPONIBLE','OCUPADA','CERRADA'))
)
GO

/*	TABLA PRODUCTOS	*/
CREATE TABLE Productos(
	IDPRODUCTO BIGINT IDENTITY(1,1),
	NOMBRE VARCHAR(100) NOT NULL,
	PRECIO MONEY NOT NULL,
	STOCK INT NOT NULL,
	ESTADO BIT DEFAULT 1,
	
	PRIMARY KEY(IDPRODUCTO)
)
GO

/*	TABLA PEDIDOS	*/
CREATE TABLE Pedidos(
	IDPEDIDO BIGINT IDENTITY(1,1),
	IDMESA BIGINT,
	IDUSUARIO BIGINT,
	--ESTADO VARCHAR(100)
	
	PRIMARY KEY(IDPEDIDO),
	FOREIGN KEY(IDMESA) REFERENCES Mesas(IDMESA),
	FOREIGN KEY(IDUSUARIO) REFERENCES Usuarios(IDUSUARIO)
)
GO

/*	TABLE DETALLES PEDIDO	*/
CREATE TABLE DetallesPedido(
	IDDETALLE BIGINT IDENTITY(1,1),
	IDPEDIDO BIGINT,
	IDPRODUCTO BIGINT,
	CANTIDAD INT NOT NULL,
	SUBTOTAL MONEY NOT NULL,

	PRIMARY KEY(IDDETALLE),
	FOREIGN KEY(IDPEDIDO) REFERENCES Pedidos(IDPEDIDO),
	FOREIGN KEY(IDPRODUCTO) REFERENCES Productos(IDPRODUCTO)
)
GO

/*	TABLA VENTAS	*/
CREATE TABLE Ventas(
	IDVENTA BIGINT IDENTITY(1,1),
	IDPEDIDO BIGINT,
	IDUSUARIO BIGINT,
	FECHA_HORA DATETIME NOT NULL DEFAULT GETDATE(),
	TOTAL MONEY NOT NULL,

	PRIMARY KEY(IDVENTA),
	FOREIGN KEY(IDPEDIDO) REFERENCES Pedidos(IDPEDIDO),
	FOREIGN KEY(IDUSUARIO) REFERENCES Usuarios(IDUSUARIO)
)
GO



/******* Inputs *******/

/*	Roles de usuario --> ampliable	*/
INSERT INTO Roles(NOMBRE)
VALUES ('GERENTE'),('MOZO')

/*	Usuarios	*/
INSERT INTO Usuarios(NOMBRE,CONTRASENIA,IDROL)
VALUES ('Master','Master',1)
INSERT INTO Usuarios(NOMBRE,CONTRASENIA,IDROL)
VALUES ('Test','Test',2)


