USE RESTO_DB
GO

/*		Usuarios		*/

CREATE VIEW vw_ListaEmpleados
AS
SELECT E.IDEMPLEADO,E.IDUSUARIO,E.NOMBRE,E.APELLIDO,E.DOCUMENTO,E.FECHA_NACIMIENTO,
	   E.FECHA_INGRESO,D.IDDIRECCION,D.CALLE,D.NUM_DIRECCION,D.LOCALIDAD,D.COD_POSTAL,
	   E.EMAIL,E.TELEFONO,U.IDROL,U.ESTADO 
FROM EMPLEADOS E
INNER JOIN Usuarios U ON E.IDUSUARIO = U.IDUSUARIO
INNER JOIN Direcciones D ON E.IDDIRECCION = D.IDDIRECCION
GO

SELECT * FROM vw_ListaEmpleados
GO

CREATE PROCEDURE sp_AgregarEmpleado(
	@pNombre VARCHAR(100),
	@pApellido VARCHAR(100),
	@pDni VARCHAR(10),
	@pFechaNac DATE,
	@pCalle VARCHAR(50),
	@pNumDir VARCHAR(4),
	@pLocalidad VARCHAR(100),
	@pCodPos VARCHAR(5),
	@pEmail VARCHAR(100),
	@pTelefono VARCHAR(15),
	@pIdRol INT
	)AS
BEGIN 
	
	DECLARE @IdUsuario BIGINT
	DECLARE @IdDireccion BIGINT

	IF EXISTS (SELECT 1 FROM Empleados WHERE DOCUMENTO = @pDNI)
	BEGIN
		RETURN
	END

	INSERT Usuarios (NOMBRE,CONTRASENIA,IDROL)
	VALUES (@pDni,@pDni,@pIdRol)

	INSERT Direcciones (CALLE,NUM_DIRECCION,LOCALIDAD,COD_POSTAL)
	VALUES (@pCalle,@pNumDir,@pLocalidad,@pCodPos)

	SELECT @IdDireccion = IDENT_CURRENT('Direcciones')
	SELECT @IdUsuario = IDENT_CURRENT('Usuarios')

	INSERT INTO Empleados(IDUSUARIO,IDDIRECCION,NOMBRE,APELLIDO,DOCUMENTO,FECHA_NACIMIENTO,EMAIL,TELEFONO)
	VALUES (@IdUsuario,@IdDireccion,@pNombre,@pApellido,@pDni,@pFechaNac,@pEmail,@pTelefono)

END
GO


/*		Productos		*/

CREATE VIEW vwListaCafeteria
AS
SELECT P.IDPRODUCTO,P.IDCATEGORIA,P.NOMBRE,P.PRECIO,P.STOCK, 
	   P.DESCRIPCION,C.TIPOCAFE,C.TAMANO,C.LECHE,C.LECHE_ALMENDRAS,P.ESTADO
	   FROM Productos P
INNER JOIN Cafeteria C ON P.IDPRODUCTO = C.IDPRODUCTO
GO

CREATE VIEW vwListaEntradas
AS
SELECT P.IDPRODUCTO,P.IDCATEGORIA,P.NOMBRE,P.PRECIO,P.STOCK, 
	   P.DESCRIPCION,E.PORCIONES,P.ESTADO
	   FROM Productos P
INNER JOIN Entradas E ON P.IDPRODUCTO = E.IDPRODUCTO
GO

CREATE VIEW vwListaComias
AS
SELECT P.IDPRODUCTO,P.IDCATEGORIA,P.NOMBRE,P.PRECIO,P.STOCK, 
	   P.DESCRIPCION,C.GUARNICION,P.ESTADO
	   FROM Productos P
INNER JOIN Comidas C ON P.IDPRODUCTO = C.IDPRODUCTO
GO

CREATE VIEW vwListaPostres
AS
SELECT P.IDPRODUCTO,P.IDCATEGORIA,P.NOMBRE,P.PRECIO,P.STOCK, 
	   P.DESCRIPCION,Po.AZUCAR,Po.GLUTEN,P.ESTADO
	   FROM Productos P
INNER JOIN Postres Po ON P.IDPRODUCTO = Po.IDPRODUCTO
GO

CREATE VIEW vwListaBebidas
AS
SELECT P.IDPRODUCTO,P.IDCATEGORIA,P.NOMBRE,P.PRECIO,P.STOCK, 
	   P.DESCRIPCION,B.ALCOHOL,B.VOLUMEN,P.ESTADO
	   FROM Productos P
INNER JOIN Bebidas B ON P.IDPRODUCTO = B.IDPRODUCTO
GO





